package Vista;

import Modelo.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexmartinez
 */
public class home extends javax.swing.JFrame {

    conexion cn = new conexion();
    Connection con = cn.getConexion();
    static DefaultComboBoxModel modelo;

    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnTodo = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnTicket = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        btnCombustible = new javax.swing.JButton();
        btnChofer = new javax.swing.JButton();
        btnDepartamento = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnVehiculo = new javax.swing.JButton();
        jpnModulo = new javax.swing.JPanel();
        jpnInicio = new javax.swing.JPanel();
        jpnTicket = new javax.swing.JPanel();
        jpnEstadisticas = new javax.swing.JPanel();
        jpnCombustible = new javax.swing.JPanel();
        lblNombreCombustible = new javax.swing.JLabel();
        lblPrecioCombustible = new javax.swing.JLabel();
        txtPrecioCombustible = new javax.swing.JTextField();
        rscProveedorCombustible = new rojerusan.RSComboMetro();
        lblProveedorCombustible = new javax.swing.JLabel();
        jsDatosCombustible = new javax.swing.JScrollPane();
        rstDatosCombustible = new rojerusan.RSTableMetro();
        btnActualizarCombustible = new javax.swing.JButton();
        btnLimpiarCombustible = new javax.swing.JButton();
        txtTipoCombustible = new javax.swing.JTextField();
        txtIdProveedorCombustible = new javax.swing.JTextField();
        txtIdCombustible = new javax.swing.JTextField();
        btnGuardarCombustible = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jpnChofer = new javax.swing.JPanel();
        lblNumEmpleadoChofer = new javax.swing.JLabel();
        txtNumEmpleadoChofer = new javax.swing.JTextField();
        lblNombreChofer = new javax.swing.JLabel();
        lblEdadChofer = new javax.swing.JLabel();
        lblNSSChofer = new javax.swing.JLabel();
        lblTipoSangreChofer = new javax.swing.JLabel();
        lblTipoLicenciaChofer = new javax.swing.JLabel();
        lblDeptoChofer = new javax.swing.JLabel();
        txtNombreChofer = new javax.swing.JTextField();
        txtEdadChofer = new javax.swing.JTextField();
        txtNSSChofer = new javax.swing.JTextField();
        rscSangreChofer = new rojerusan.RSComboMetro();
        rscLicenciaChofer = new rojerusan.RSComboMetro();
        rscDeptoChofer = new rojerusan.RSComboMetro();
        jsDatosChofer = new javax.swing.JScrollPane();
        rstDatosChofer = new rojerusan.RSTableMetro();
        btnGuardarChofer = new javax.swing.JButton();
        btnEliminarChofer = new javax.swing.JButton();
        btnLimpiarChofer = new javax.swing.JButton();
        btnActualizarChofer = new javax.swing.JButton();
        lblMetodoPagoChofer = new javax.swing.JLabel();
        rscMetodoPagoChofer = new rojerusan.RSComboMetro();
        txtIdDeptoChofer = new javax.swing.JTextField();
        txtIdChofer = new javax.swing.JTextField();
        jpnDepartamento = new javax.swing.JPanel();
        lblNombreDepto = new javax.swing.JLabel();
        txtNombredepto = new javax.swing.JTextField();
        lblEncargadoDepto = new javax.swing.JLabel();
        txtEncargadoDepto = new javax.swing.JTextField();
        btnGuardarDepto = new javax.swing.JButton();
        btnActualizarDepto = new javax.swing.JButton();
        btnEliminarDepto = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jsDatosDepto = new javax.swing.JScrollPane();
        rstDatosDepto = new rojerusan.RSTableMetro();
        txtIdDepto = new javax.swing.JTextField();
        jpnProveedor = new javax.swing.JPanel();
        lblNombreProveedor = new javax.swing.JLabel();
        txtNombreProveedor = new javax.swing.JTextField();
        lblDireccionProveedor = new javax.swing.JLabel();
        lblRFCProveedor = new javax.swing.JLabel();
        lblTelefonoProveedor = new javax.swing.JLabel();
        txtTelefonoProveedor = new javax.swing.JTextField();
        txtRFCProveedor = new javax.swing.JTextField();
        txtDireccionProveedor = new javax.swing.JTextField();
        btnGuardarProveedor = new javax.swing.JButton();
        btnActualizarProveedor = new javax.swing.JButton();
        btnBorrarProveedor = new javax.swing.JButton();
        btnLimpiarProveedor = new javax.swing.JButton();
        jsDatosProveedor = new javax.swing.JScrollPane();
        rstDatosProveedor = new rojerusan.RSTableMetro();
        txtIdProveedor = new javax.swing.JTextField();
        jpnVehiculo = new javax.swing.JPanel();
        lblModeloVehiculo = new javax.swing.JLabel();
        txtModeloVehiculo = new javax.swing.JTextField();
        lblColorVehiculo = new javax.swing.JLabel();
        lblAnioVehiculo = new javax.swing.JLabel();
        lblPlacaVehiculo = new javax.swing.JLabel();
        lblTipoVehiculo = new javax.swing.JLabel();
        lblDeptoVehiculo = new javax.swing.JLabel();
        lblMarcaVehiculo = new javax.swing.JLabel();
        txtPlacavehiculo = new javax.swing.JTextField();
        txtColorVehiculo = new javax.swing.JTextField();
        txtMarcaVehiculo = new javax.swing.JTextField();
        rscTipoVehiculo = new rojerusan.RSComboMetro();
        rscDeptoVehiculo = new rojerusan.RSComboMetro();
        jScrollPane1 = new javax.swing.JScrollPane();
        rstDatosVehiculo = new rojerusan.RSTableMetro();
        btnGuardarVehiculo = new javax.swing.JButton();
        btnActualizarVehiculo = new javax.swing.JButton();
        btnEliminarVehiculo = new javax.swing.JButton();
        btnLimpiarVehiculo = new javax.swing.JButton();
        txtIdDeptoVehiculo = new javax.swing.JTextField();
        txtIdVehiculo = new javax.swing.JTextField();
        txtAnioVehiculo = new javax.swing.JTextField();
        jpnBarra = new javax.swing.JPanel();
        jpnTitulos = new javax.swing.JPanel();
        jpnTituloInicio = new javax.swing.JPanel();
        lblTituloInicio = new javax.swing.JLabel();
        jpnTituloTicket = new javax.swing.JPanel();
        lblTituloTicket = new javax.swing.JLabel();
        jpnTituloEstadisticas = new javax.swing.JPanel();
        lblTituloEstadisticas = new javax.swing.JLabel();
        jpnTituloCombustible = new javax.swing.JPanel();
        lblTituloCombustible = new javax.swing.JLabel();
        jpnTituloChofer = new javax.swing.JPanel();
        lblTituloChofer = new javax.swing.JLabel();
        jpnTituloDepto = new javax.swing.JPanel();
        lblTituloDepto = new javax.swing.JLabel();
        jpnTituloProveedor = new javax.swing.JPanel();
        lblTituloProveedor = new javax.swing.JLabel();
        jpnTituloVehiculo = new javax.swing.JPanel();
        lblTituloVehiculo = new javax.swing.JLabel();
        jpnControl = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnTodo.setBackground(new java.awt.Color(255, 255, 255));
        jpnTodo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnMenu.setBackground(new java.awt.Color(0, 0, 0));
        jpnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otras_Imagenes/aguja de gasolina 170x170.png"))); // NOI18N
        jpnMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 170, 170));

        btnInicio.setText("Inicio");
        jpnMenu.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 230, 40));

        btnTicket.setText("Ticket");
        btnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketActionPerformed(evt);
            }
        });
        jpnMenu.add(btnTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 40));

        btnEstadisticas.setText("Estadisticas");
        jpnMenu.add(btnEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 230, 40));

        btnCombustible.setText("Combustible");
        jpnMenu.add(btnCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 230, 40));

        btnChofer.setText("Chofer");
        jpnMenu.add(btnChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 230, 40));

        btnDepartamento.setText("Departamentos");
        jpnMenu.add(btnDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 230, 40));

        btnProveedor.setText("Proveedor");
        jpnMenu.add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 230, 40));

        btnVehiculo.setText("Vehiculo");
        jpnMenu.add(btnVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 230, 40));

        jpnTodo.add(jpnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 700));

        jpnModulo.setBackground(new java.awt.Color(102, 102, 102));
        jpnModulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnInicio.setBackground(new java.awt.Color(102, 102, 102));
        jpnInicio.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 5, new java.awt.Color(0, 0, 0)));
        jpnModulo.add(jpnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 660));

        jpnTicket.setBackground(new java.awt.Color(102, 102, 102));
        jpnTicket.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 5, new java.awt.Color(0, 0, 0)));
        jpnModulo.add(jpnTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 660));

        jpnEstadisticas.setBackground(new java.awt.Color(102, 102, 102));
        jpnEstadisticas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 5, new java.awt.Color(0, 0, 0)));
        jpnModulo.add(jpnEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 660));

        jpnCombustible.setBackground(new java.awt.Color(102, 102, 102));
        jpnCombustible.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 5, new java.awt.Color(0, 0, 0)));
        jpnCombustible.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreCombustible.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        lblNombreCombustible.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreCombustible.setText("Combustible:");
        jpnCombustible.add(lblNombreCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 140, 30));

        lblPrecioCombustible.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        lblPrecioCombustible.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioCombustible.setText("Precio:");
        jpnCombustible.add(lblPrecioCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        txtPrecioCombustible.setBackground(new java.awt.Color(102, 102, 102));
        txtPrecioCombustible.setFont(new java.awt.Font("Ayuthaya", 0, 18)); // NOI18N
        txtPrecioCombustible.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecioCombustible.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jpnCombustible.add(txtPrecioCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 200, 30));

        rscProveedorCombustible.setBackground(new java.awt.Color(102, 102, 102));
        rscProveedorCombustible.setColorArrow(new java.awt.Color(102, 102, 102));
        rscProveedorCombustible.setColorBorde(new java.awt.Color(255, 255, 255));
        rscProveedorCombustible.setColorFondo(new java.awt.Color(102, 102, 102));
        rscProveedorCombustible.setFont(new java.awt.Font("Ayuthaya", 1, 14)); // NOI18N
        rscProveedorCombustible.setName(""); // NOI18N
        jpnCombustible.add(rscProveedorCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 220, 30));

        lblProveedorCombustible.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblProveedorCombustible.setForeground(new java.awt.Color(255, 255, 255));
        lblProveedorCombustible.setText("Proveedor:");
        jpnCombustible.add(lblProveedorCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 110, 30));

        rstDatosCombustible.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "COMBUSTIBLE", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rstDatosCombustible.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        rstDatosCombustible.setColorBordeFilas(new java.awt.Color(102, 102, 102));
        rstDatosCombustible.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        rstDatosCombustible.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        rstDatosCombustible.setColorSelBackgound(new java.awt.Color(102, 102, 102));
        rstDatosCombustible.setFuenteFilas(new java.awt.Font("Ayuthaya", 0, 18)); // NOI18N
        rstDatosCombustible.setFuenteFilasSelect(new java.awt.Font("Ayuthaya", 1, 18)); // NOI18N
        rstDatosCombustible.setFuenteHead(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        rstDatosCombustible.setGridColor(new java.awt.Color(0, 0, 0));
        rstDatosCombustible.setRowHeight(20);
        rstDatosCombustible.setRowMargin(0);
        rstDatosCombustible.setSelectionBackground(new java.awt.Color(102, 102, 102));
        rstDatosCombustible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rstDatosCombustibleMouseClicked(evt);
            }
        });
        jsDatosCombustible.setViewportView(rstDatosCombustible);

        jpnCombustible.add(jsDatosCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 450, 560));

        btnActualizarCombustible.setText("Actualizar");
        jpnCombustible.add(btnActualizarCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        btnLimpiarCombustible.setText("Limpiar");
        jpnCombustible.add(btnLimpiarCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, -1));

        txtTipoCombustible.setBackground(new java.awt.Color(102, 102, 102));
        txtTipoCombustible.setFont(new java.awt.Font("Ayuthaya", 0, 18)); // NOI18N
        txtTipoCombustible.setForeground(new java.awt.Color(255, 255, 255));
        txtTipoCombustible.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        txtTipoCombustible.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTipoCombustibleKeyReleased(evt);
            }
        });
        jpnCombustible.add(txtTipoCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 220, 30));

        txtIdProveedorCombustible.setText("Proveedor");
        jpnCombustible.add(txtIdProveedorCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, -1, -1));

        txtIdCombustible.setText("Combustible");
        jpnCombustible.add(txtIdCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, -1, -1));

        btnGuardarCombustible.setText("Guardar");
        jpnCombustible.add(btnGuardarCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        jTextField1.setBackground(new java.awt.Color(102, 102, 102));
        jTextField1.setFont(new java.awt.Font("Ayuthaya", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField1.setText("$");
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jpnCombustible.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 10, 30));

        jpnModulo.add(jpnCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 660));

        jpnChofer.setBackground(new java.awt.Color(102, 102, 102));
        jpnChofer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 5, new java.awt.Color(0, 0, 0)));
        jpnChofer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumEmpleadoChofer.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblNumEmpleadoChofer.setForeground(new java.awt.Color(255, 255, 255));
        lblNumEmpleadoChofer.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNumEmpleadoChofer.setText("Num Empleado:");
        jpnChofer.add(lblNumEmpleadoChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 160, 30));

        txtNumEmpleadoChofer.setBackground(new java.awt.Color(102, 102, 102));
        txtNumEmpleadoChofer.setFont(new java.awt.Font("Ayuthaya", 0, 18)); // NOI18N
        txtNumEmpleadoChofer.setForeground(new java.awt.Color(255, 255, 255));
        txtNumEmpleadoChofer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jpnChofer.add(txtNumEmpleadoChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 240, 30));

        lblNombreChofer.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblNombreChofer.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreChofer.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNombreChofer.setText("Nombre:");
        jpnChofer.add(lblNombreChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 160, 30));

        lblEdadChofer.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblEdadChofer.setForeground(new java.awt.Color(255, 255, 255));
        lblEdadChofer.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEdadChofer.setText("Edad:");
        jpnChofer.add(lblEdadChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 160, 30));

        lblNSSChofer.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblNSSChofer.setForeground(new java.awt.Color(255, 255, 255));
        lblNSSChofer.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNSSChofer.setText("NSS:");
        jpnChofer.add(lblNSSChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 160, 30));

        lblTipoSangreChofer.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblTipoSangreChofer.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoSangreChofer.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTipoSangreChofer.setText("Sangre:");
        jpnChofer.add(lblTipoSangreChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 160, 30));

        lblTipoLicenciaChofer.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblTipoLicenciaChofer.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoLicenciaChofer.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTipoLicenciaChofer.setText("Tipo de Licencia:");
        jpnChofer.add(lblTipoLicenciaChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 160, 30));

        lblDeptoChofer.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblDeptoChofer.setForeground(new java.awt.Color(255, 255, 255));
        lblDeptoChofer.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDeptoChofer.setText("Departamento:");
        jpnChofer.add(lblDeptoChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 160, 30));

        txtNombreChofer.setBackground(new java.awt.Color(102, 102, 102));
        txtNombreChofer.setFont(new java.awt.Font("Ayuthaya", 0, 18)); // NOI18N
        txtNombreChofer.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreChofer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreChofer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jpnChofer.add(txtNombreChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 240, 30));

        txtEdadChofer.setBackground(new java.awt.Color(102, 102, 102));
        txtEdadChofer.setFont(new java.awt.Font("Ayuthaya", 0, 18)); // NOI18N
        txtEdadChofer.setForeground(new java.awt.Color(255, 255, 255));
        txtEdadChofer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jpnChofer.add(txtEdadChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 240, 30));

        txtNSSChofer.setBackground(new java.awt.Color(102, 102, 102));
        txtNSSChofer.setFont(new java.awt.Font("Ayuthaya", 0, 18)); // NOI18N
        txtNSSChofer.setForeground(new java.awt.Color(255, 255, 255));
        txtNSSChofer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jpnChofer.add(txtNSSChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 240, 30));

        rscSangreChofer.setBackground(new java.awt.Color(102, 102, 102));
        rscSangreChofer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Selecciona Uno--", "A+", "B+", "O+", "AB+", "A-", "B-", "O-", "AB-" }));
        rscSangreChofer.setColorArrow(new java.awt.Color(102, 102, 102));
        rscSangreChofer.setColorBorde(new java.awt.Color(255, 255, 255));
        rscSangreChofer.setColorFondo(new java.awt.Color(102, 102, 102));
        rscSangreChofer.setFont(new java.awt.Font("Ayuthaya", 0, 14)); // NOI18N
        jpnChofer.add(rscSangreChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 250, -1));

        rscLicenciaChofer.setBackground(new java.awt.Color(102, 102, 102));
        rscLicenciaChofer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Selecciona Uno--", "A", "B", "C", "D" }));
        rscLicenciaChofer.setColorArrow(new java.awt.Color(102, 102, 102));
        rscLicenciaChofer.setColorBorde(new java.awt.Color(255, 255, 255));
        rscLicenciaChofer.setColorFondo(new java.awt.Color(102, 102, 102));
        rscLicenciaChofer.setFont(new java.awt.Font("Ayuthaya", 0, 14)); // NOI18N
        jpnChofer.add(rscLicenciaChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 250, -1));

        rscDeptoChofer.setBackground(new java.awt.Color(102, 102, 102));
        rscDeptoChofer.setColorArrow(new java.awt.Color(102, 102, 102));
        rscDeptoChofer.setColorBorde(new java.awt.Color(255, 255, 255));
        rscDeptoChofer.setColorFondo(new java.awt.Color(102, 102, 102));
        rscDeptoChofer.setFont(new java.awt.Font("Ayuthaya", 0, 14)); // NOI18N
        jpnChofer.add(rscDeptoChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 250, -1));

        rstDatosChofer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NUM. EMPLEADO", "NOMBRE", "DEPARTAMENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rstDatosChofer.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        rstDatosChofer.setColorBordeFilas(new java.awt.Color(102, 102, 102));
        rstDatosChofer.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        rstDatosChofer.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        rstDatosChofer.setColorSelBackgound(new java.awt.Color(102, 102, 102));
        rstDatosChofer.setFuenteFilas(new java.awt.Font("Ayuthaya", 0, 18)); // NOI18N
        rstDatosChofer.setFuenteFilasSelect(new java.awt.Font("Ayuthaya", 1, 18)); // NOI18N
        rstDatosChofer.setFuenteHead(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        rstDatosChofer.setGridColor(new java.awt.Color(0, 0, 0));
        rstDatosChofer.setRowHeight(20);
        rstDatosChofer.setRowMargin(0);
        rstDatosChofer.setSelectionBackground(new java.awt.Color(102, 102, 102));
        rstDatosChofer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rstDatosChoferMouseClicked(evt);
            }
        });
        jsDatosChofer.setViewportView(rstDatosChofer);

        jpnChofer.add(jsDatosChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 550, 560));

        btnGuardarChofer.setText("Guardar");
        jpnChofer.add(btnGuardarChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        btnEliminarChofer.setText("Eliminar");
        jpnChofer.add(btnEliminarChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, -1, -1));

        btnLimpiarChofer.setText("Limpiar");
        jpnChofer.add(btnLimpiarChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, -1, -1));

        btnActualizarChofer.setText("Actualizar");
        jpnChofer.add(btnActualizarChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, -1, -1));

        lblMetodoPagoChofer.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblMetodoPagoChofer.setForeground(new java.awt.Color(255, 255, 255));
        lblMetodoPagoChofer.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMetodoPagoChofer.setText("Metodo de Pago:");
        jpnChofer.add(lblMetodoPagoChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 170, 30));

        rscMetodoPagoChofer.setBackground(new java.awt.Color(102, 102, 102));
        rscMetodoPagoChofer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Seleccione uno--", "TARJETA", "EFECTIVO" }));
        rscMetodoPagoChofer.setColorArrow(new java.awt.Color(102, 102, 102));
        rscMetodoPagoChofer.setColorBorde(new java.awt.Color(255, 255, 255));
        rscMetodoPagoChofer.setColorFondo(new java.awt.Color(102, 102, 102));
        rscMetodoPagoChofer.setFont(new java.awt.Font("Ayuthaya", 0, 14)); // NOI18N
        jpnChofer.add(rscMetodoPagoChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 250, -1));

        txtIdDeptoChofer.setEditable(false);
        txtIdDeptoChofer.setText("Departamento");
        jpnChofer.add(txtIdDeptoChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 100, -1));

        txtIdChofer.setText("Chofer");
        jpnChofer.add(txtIdChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 110, -1));

        jpnModulo.add(jpnChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 660));

        jpnDepartamento.setBackground(new java.awt.Color(102, 102, 102));
        jpnDepartamento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 5, new java.awt.Color(0, 0, 0)));
        jpnDepartamento.setName("jpnDepartamento"); // NOI18N
        jpnDepartamento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreDepto.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblNombreDepto.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreDepto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNombreDepto.setText("Departamento:");
        jpnDepartamento.add(lblNombreDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 150, 30));

        txtNombredepto.setBackground(new java.awt.Color(102, 102, 102));
        txtNombredepto.setFont(new java.awt.Font("Ayuthaya", 0, 18)); // NOI18N
        txtNombredepto.setForeground(new java.awt.Color(255, 255, 255));
        txtNombredepto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jpnDepartamento.add(txtNombredepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 400, 30));

        lblEncargadoDepto.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblEncargadoDepto.setForeground(new java.awt.Color(255, 255, 255));
        lblEncargadoDepto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEncargadoDepto.setText("Encargado:");
        jpnDepartamento.add(lblEncargadoDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 150, 30));

        txtEncargadoDepto.setBackground(new java.awt.Color(102, 102, 102));
        txtEncargadoDepto.setFont(new java.awt.Font("Ayuthaya", 0, 18)); // NOI18N
        txtEncargadoDepto.setForeground(new java.awt.Color(255, 255, 255));
        txtEncargadoDepto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jpnDepartamento.add(txtEncargadoDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 400, 30));

        btnGuardarDepto.setText("Guardar");
        jpnDepartamento.add(btnGuardarDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        btnActualizarDepto.setText("Actualizar");
        jpnDepartamento.add(btnActualizarDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        btnEliminarDepto.setText("Eliminar");
        jpnDepartamento.add(btnEliminarDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        btnLimpiar.setText("Limpiar");
        jpnDepartamento.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        rstDatosDepto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "DEPARTAMENTO", "ENCARGADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rstDatosDepto.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        rstDatosDepto.setColorBordeFilas(new java.awt.Color(102, 102, 102));
        rstDatosDepto.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        rstDatosDepto.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        rstDatosDepto.setColorSelBackgound(new java.awt.Color(102, 102, 102));
        rstDatosDepto.setFuenteFilas(new java.awt.Font("Ayuthaya", 0, 18)); // NOI18N
        rstDatosDepto.setFuenteFilasSelect(new java.awt.Font("Ayuthaya", 1, 18)); // NOI18N
        rstDatosDepto.setFuenteHead(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        rstDatosDepto.setGridColor(new java.awt.Color(0, 0, 0));
        rstDatosDepto.setRowHeight(20);
        rstDatosDepto.setRowMargin(0);
        rstDatosDepto.setSelectionBackground(new java.awt.Color(102, 102, 102));
        rstDatosDepto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rstDatosDeptoMouseClicked(evt);
            }
        });
        jsDatosDepto.setViewportView(rstDatosDepto);

        jpnDepartamento.add(jsDatosDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 700, 220));

        txtIdDepto.setEnabled(false);
        jpnDepartamento.add(txtIdDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 140, -1));

        jpnModulo.add(jpnDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 660));

        jpnProveedor.setBackground(new java.awt.Color(102, 102, 102));
        jpnProveedor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 5, new java.awt.Color(0, 0, 0)));
        jpnProveedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreProveedor.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblNombreProveedor.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreProveedor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNombreProveedor.setText("Razon social:");
        jpnProveedor.add(lblNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 170, 30));

        txtNombreProveedor.setBackground(new java.awt.Color(102, 102, 102));
        txtNombreProveedor.setFont(new java.awt.Font("Ayuthaya", 1, 18)); // NOI18N
        txtNombreProveedor.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreProveedor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        txtNombreProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreProveedorKeyReleased(evt);
            }
        });
        jpnProveedor.add(txtNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 300, -1));

        lblDireccionProveedor.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblDireccionProveedor.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccionProveedor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDireccionProveedor.setText("Dirección:");
        jpnProveedor.add(lblDireccionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 170, 30));

        lblRFCProveedor.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblRFCProveedor.setForeground(new java.awt.Color(255, 255, 255));
        lblRFCProveedor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblRFCProveedor.setText("RFC:");
        jpnProveedor.add(lblRFCProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 170, 30));

        lblTelefonoProveedor.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblTelefonoProveedor.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefonoProveedor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTelefonoProveedor.setText("Telefono:");
        jpnProveedor.add(lblTelefonoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 170, 30));

        txtTelefonoProveedor.setBackground(new java.awt.Color(102, 102, 102));
        txtTelefonoProveedor.setFont(new java.awt.Font("Ayuthaya", 1, 18)); // NOI18N
        txtTelefonoProveedor.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefonoProveedor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        txtTelefonoProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoProveedorKeyTyped(evt);
            }
        });
        jpnProveedor.add(txtTelefonoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 300, -1));

        txtRFCProveedor.setBackground(new java.awt.Color(102, 102, 102));
        txtRFCProveedor.setFont(new java.awt.Font("Ayuthaya", 1, 18)); // NOI18N
        txtRFCProveedor.setForeground(new java.awt.Color(255, 255, 255));
        txtRFCProveedor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        txtRFCProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRFCProveedorKeyReleased(evt);
            }
        });
        jpnProveedor.add(txtRFCProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 300, -1));

        txtDireccionProveedor.setBackground(new java.awt.Color(102, 102, 102));
        txtDireccionProveedor.setFont(new java.awt.Font("Ayuthaya", 1, 18)); // NOI18N
        txtDireccionProveedor.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccionProveedor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        txtDireccionProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDireccionProveedorKeyReleased(evt);
            }
        });
        jpnProveedor.add(txtDireccionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 300, -1));

        btnGuardarProveedor.setText("Guardar");
        jpnProveedor.add(btnGuardarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        btnActualizarProveedor.setText("Actualizar");
        jpnProveedor.add(btnActualizarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        btnBorrarProveedor.setText("Borrar");
        jpnProveedor.add(btnBorrarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        btnLimpiarProveedor.setText("Limpiar");
        jpnProveedor.add(btnLimpiarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        rstDatosProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "PROVEEDOR", "RFC"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rstDatosProveedor.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        rstDatosProveedor.setColorBordeFilas(new java.awt.Color(102, 102, 102));
        rstDatosProveedor.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        rstDatosProveedor.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        rstDatosProveedor.setColorSelBackgound(new java.awt.Color(102, 102, 102));
        rstDatosProveedor.setFuenteFilas(new java.awt.Font("Ayuthaya", 0, 18)); // NOI18N
        rstDatosProveedor.setFuenteFilasSelect(new java.awt.Font("Ayuthaya", 1, 18)); // NOI18N
        rstDatosProveedor.setFuenteHead(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        rstDatosProveedor.setGridColor(new java.awt.Color(0, 0, 0));
        rstDatosProveedor.setRowHeight(20);
        rstDatosProveedor.setRowMargin(0);
        rstDatosProveedor.setSelectionBackground(new java.awt.Color(102, 102, 102));
        rstDatosProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rstDatosProveedorMouseClicked(evt);
            }
        });
        jsDatosProveedor.setViewportView(rstDatosProveedor);

        jpnProveedor.add(jsDatosProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        txtIdProveedor.setText("id_proveedor");
        jpnProveedor.add(txtIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, -1));

        jpnModulo.add(jpnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 660));

        jpnVehiculo.setBackground(new java.awt.Color(102, 102, 102));
        jpnVehiculo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 5, new java.awt.Color(0, 0, 0)));
        jpnVehiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblModeloVehiculo.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblModeloVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblModeloVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblModeloVehiculo.setText("Modelo:");
        jpnVehiculo.add(lblModeloVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, 30));

        txtModeloVehiculo.setBackground(new java.awt.Color(102, 102, 102));
        txtModeloVehiculo.setFont(new java.awt.Font("Ayuthaya", 0, 18)); // NOI18N
        txtModeloVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        txtModeloVehiculo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jpnVehiculo.add(txtModeloVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 300, 30));

        lblColorVehiculo.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblColorVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblColorVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblColorVehiculo.setText("Color:");
        jpnVehiculo.add(lblColorVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 150, 30));

        lblAnioVehiculo.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblAnioVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblAnioVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAnioVehiculo.setText("Año:");
        jpnVehiculo.add(lblAnioVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 150, 30));

        lblPlacaVehiculo.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblPlacaVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblPlacaVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPlacaVehiculo.setText("Placa:");
        jpnVehiculo.add(lblPlacaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 30));

        lblTipoVehiculo.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblTipoVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTipoVehiculo.setText("Tipo:");
        jpnVehiculo.add(lblTipoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 150, 30));

        lblDeptoVehiculo.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblDeptoVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblDeptoVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDeptoVehiculo.setText("Departamento:");
        jpnVehiculo.add(lblDeptoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 150, 30));

        lblMarcaVehiculo.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblMarcaVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblMarcaVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMarcaVehiculo.setText("Marca:");
        jpnVehiculo.add(lblMarcaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, 30));

        txtPlacavehiculo.setBackground(new java.awt.Color(102, 102, 102));
        txtPlacavehiculo.setFont(new java.awt.Font("Ayuthaya", 0, 18)); // NOI18N
        txtPlacavehiculo.setForeground(new java.awt.Color(255, 255, 255));
        txtPlacavehiculo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jpnVehiculo.add(txtPlacavehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 300, 30));

        txtColorVehiculo.setBackground(new java.awt.Color(102, 102, 102));
        txtColorVehiculo.setFont(new java.awt.Font("Ayuthaya", 0, 18)); // NOI18N
        txtColorVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        txtColorVehiculo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jpnVehiculo.add(txtColorVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 300, 30));

        txtMarcaVehiculo.setBackground(new java.awt.Color(102, 102, 102));
        txtMarcaVehiculo.setFont(new java.awt.Font("Ayuthaya", 0, 18)); // NOI18N
        txtMarcaVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        txtMarcaVehiculo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jpnVehiculo.add(txtMarcaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 300, 30));

        rscTipoVehiculo.setBackground(new java.awt.Color(102, 102, 102));
        rscTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Seleccione uno--", "Particular", "Ayuntamiento" }));
        rscTipoVehiculo.setColorArrow(new java.awt.Color(102, 102, 102));
        rscTipoVehiculo.setColorBorde(new java.awt.Color(255, 255, 255));
        rscTipoVehiculo.setColorFondo(new java.awt.Color(102, 102, 102));
        rscTipoVehiculo.setFont(new java.awt.Font("Ayuthaya", 0, 14)); // NOI18N
        jpnVehiculo.add(rscTipoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 300, 30));

        rscDeptoVehiculo.setBackground(new java.awt.Color(102, 102, 102));
        rscDeptoVehiculo.setColorArrow(new java.awt.Color(102, 102, 102));
        rscDeptoVehiculo.setColorBorde(new java.awt.Color(255, 255, 255));
        rscDeptoVehiculo.setColorFondo(new java.awt.Color(102, 102, 102));
        rscDeptoVehiculo.setFont(new java.awt.Font("Ayuthaya", 0, 14)); // NOI18N
        jpnVehiculo.add(rscDeptoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 300, 30));

        rstDatosVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MARCA", "MODELO", "COLOR", "PLACA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rstDatosVehiculo.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        rstDatosVehiculo.setColorBordeFilas(new java.awt.Color(102, 102, 102));
        rstDatosVehiculo.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        rstDatosVehiculo.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        rstDatosVehiculo.setColorSelBackgound(new java.awt.Color(102, 102, 102));
        rstDatosVehiculo.setFuenteFilas(new java.awt.Font("Ayuthaya", 1, 18)); // NOI18N
        rstDatosVehiculo.setFuenteFilasSelect(new java.awt.Font("Ayuthaya", 1, 18)); // NOI18N
        rstDatosVehiculo.setFuenteHead(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        rstDatosVehiculo.setGridColor(new java.awt.Color(0, 0, 0));
        rstDatosVehiculo.setRowHeight(20);
        rstDatosVehiculo.setRowMargin(0);
        rstDatosVehiculo.setSelectionBackground(new java.awt.Color(102, 102, 102));
        rstDatosVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rstDatosVehiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rstDatosVehiculo);

        jpnVehiculo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        btnGuardarVehiculo.setText("Guardar");
        jpnVehiculo.add(btnGuardarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        btnActualizarVehiculo.setText("Actualizar");
        jpnVehiculo.add(btnActualizarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, -1));

        btnEliminarVehiculo.setText("Eliminar");
        jpnVehiculo.add(btnEliminarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, -1, -1));

        btnLimpiarVehiculo.setText("Limpiar");
        jpnVehiculo.add(btnLimpiarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, -1, -1));

        txtIdDeptoVehiculo.setText("depto");
        jpnVehiculo.add(txtIdDeptoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 60, -1));

        txtIdVehiculo.setText("Vehiculo");
        jpnVehiculo.add(txtIdVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 70, -1));

        txtAnioVehiculo.setBackground(new java.awt.Color(102, 102, 102));
        txtAnioVehiculo.setFont(new java.awt.Font("Ayuthaya", 0, 18)); // NOI18N
        txtAnioVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        txtAnioVehiculo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jpnVehiculo.add(txtAnioVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 300, 30));

        jpnModulo.add(jpnVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 660));

        jpnTodo.add(jpnModulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 1070, 660));

        jpnBarra.setBackground(new java.awt.Color(255, 255, 255));
        jpnBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnTitulos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnTituloInicio.setBackground(new java.awt.Color(0, 0, 0));
        jpnTituloInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloInicio.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblTituloInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloInicio.setText("INICIO");
        jpnTituloInicio.add(lblTituloInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 170, 40));

        jpnTitulos.add(jpnTituloInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 40));

        jpnTituloTicket.setBackground(new java.awt.Color(0, 0, 0));
        jpnTituloTicket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloTicket.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblTituloTicket.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloTicket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTicket.setText("TIKECT");
        jpnTituloTicket.add(lblTituloTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 170, 40));

        jpnTitulos.add(jpnTituloTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 40));

        jpnTituloEstadisticas.setBackground(new java.awt.Color(0, 0, 0));
        jpnTituloEstadisticas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloEstadisticas.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblTituloEstadisticas.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloEstadisticas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloEstadisticas.setText("ESTADISTICAS");
        jpnTituloEstadisticas.add(lblTituloEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 170, 40));

        jpnTitulos.add(jpnTituloEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 40));

        jpnTituloCombustible.setBackground(new java.awt.Color(0, 0, 0));
        jpnTituloCombustible.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloCombustible.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblTituloCombustible.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloCombustible.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCombustible.setText("COMBUSTIBLE");
        jpnTituloCombustible.add(lblTituloCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 170, 40));

        jpnTitulos.add(jpnTituloCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 40));

        jpnTituloChofer.setBackground(new java.awt.Color(0, 0, 0));
        jpnTituloChofer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloChofer.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        lblTituloChofer.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloChofer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloChofer.setText("CHOFER");
        jpnTituloChofer.add(lblTituloChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 170, 40));

        jpnTitulos.add(jpnTituloChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 40));

        jpnTituloDepto.setBackground(new java.awt.Color(0, 0, 0));
        jpnTituloDepto.setForeground(new java.awt.Color(255, 255, 255));
        jpnTituloDepto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloDepto.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblTituloDepto.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloDepto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloDepto.setText("DEPARTAMENTOS");
        jpnTituloDepto.add(lblTituloDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 170, 40));

        jpnTitulos.add(jpnTituloDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 40));

        jpnTituloProveedor.setBackground(new java.awt.Color(0, 0, 0));
        jpnTituloProveedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloProveedor.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblTituloProveedor.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloProveedor.setText("PROVEEDORES");
        jpnTituloProveedor.add(lblTituloProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 170, 40));

        jpnTitulos.add(jpnTituloProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 40));

        jpnTituloVehiculo.setBackground(new java.awt.Color(0, 0, 0));
        jpnTituloVehiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloVehiculo.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        lblTituloVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloVehiculo.setText("VEHICULOS");
        jpnTituloVehiculo.add(lblTituloVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 170, 40));

        jpnTitulos.add(jpnTituloVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 40));

        jpnBarra.add(jpnTitulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 40));

        jpnControl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizar.setText("M");
        jpnControl.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        btnCerrar.setText("C");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jpnControl.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        jpnBarra.add(jpnControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 80, 40));

        jpnTodo.add(jpnBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 1070, 40));

        getContentPane().add(jpnTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rstDatosDeptoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rstDatosDeptoMouseClicked
        DefaultTableModel model = (DefaultTableModel) rstDatosDepto.getModel();
        int fila = rstDatosDepto.getSelectedRow();

        txtNombredepto.setText(rstDatosDepto.getValueAt(fila, 1).toString());
        txtEncargadoDepto.setText(rstDatosDepto.getValueAt(fila, 2).toString());
        txtIdDepto.setText(rstDatosDepto.getValueAt(fila, 0).toString());
    }//GEN-LAST:event_rstDatosDeptoMouseClicked

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void rstDatosChoferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rstDatosChoferMouseClicked
        DefaultTableModel model = (DefaultTableModel) rstDatosChofer.getModel();
        int fila = rstDatosChofer.getSelectedRow();
        txtNumEmpleadoChofer.setText(rstDatosChofer.getValueAt(fila, 0).toString());
        txtNombreChofer.setText(rstDatosChofer.getValueAt(fila, 1).toString());
        txtIdDeptoChofer.setText(rstDatosChofer.getValueAt(fila, 2).toString());
        consultarDeptoChofer();
        consultarDatosChofer();
    }//GEN-LAST:event_rstDatosChoferMouseClicked

    private void rstDatosProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rstDatosProveedorMouseClicked
        DefaultTableModel model = (DefaultTableModel) rstDatosProveedor.getModel();
        int fila = rstDatosProveedor.getSelectedRow();
        txtIdProveedor.setText(rstDatosProveedor.getValueAt(fila, 0).toString());
        consultarDatosProveedor();
    }//GEN-LAST:event_rstDatosProveedorMouseClicked

    private void txtDireccionProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionProveedorKeyReleased
        txtDireccionProveedor.setText(txtDireccionProveedor.getText().toUpperCase());
    }//GEN-LAST:event_txtDireccionProveedorKeyReleased

    private void txtRFCProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFCProveedorKeyReleased
        txtRFCProveedor.setText(txtRFCProveedor.getText().toUpperCase());
    }//GEN-LAST:event_txtRFCProveedorKeyReleased

    private void txtTelefonoProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoProveedorKeyTyped
        char validar = evt.getKeyChar();
        if (!Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoProveedorKeyTyped

    private void txtNombreProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProveedorKeyReleased
        txtNombreProveedor.setText(txtNombreProveedor.getText().toUpperCase());
    }//GEN-LAST:event_txtNombreProveedorKeyReleased

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTicketActionPerformed

    private void txtTipoCombustibleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoCombustibleKeyReleased
        txtTipoCombustible.setText(txtTipoCombustible.getText().toUpperCase());
    }//GEN-LAST:event_txtTipoCombustibleKeyReleased

    private void rstDatosCombustibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rstDatosCombustibleMouseClicked
        DefaultTableModel model = (DefaultTableModel) rstDatosCombustible.getModel();
        int fila = rstDatosCombustible.getSelectedRow();
        txtIdCombustible.setText(rstDatosCombustible.getValueAt(fila, 0).toString());
        consultarDatosCombustible();
        consultarProveedorCombustible();
    }//GEN-LAST:event_rstDatosCombustibleMouseClicked

    private void rstDatosVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rstDatosVehiculoMouseClicked
        DefaultTableModel model = (DefaultTableModel) rstDatosVehiculo.getModel();
        int fila = rstDatosVehiculo.getSelectedRow();
        txtPlacavehiculo.setText(rstDatosVehiculo.getValueAt(fila, 3).toString());
        consultarIdvehiculo();
    }//GEN-LAST:event_rstDatosVehiculoMouseClicked

    //Metodos de consulta------------------------------------------------------>
    public void consultarDepartamentos() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("DEPARTAMENTO");
        modelo.addColumn("ENCARGADO");
        rstDatosDepto.setModel(modelo);

        String sql = "SELECT * FROM departamento";

        String datos[] = new String[3];
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                modelo.addRow(datos);
            }
            rstDatosDepto.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void consultarChofer() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("NUM. EMPLEADO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("DEPARTAMENTO");
        rstDatosChofer.setModel(modelo);

        String sql = "SELECT numero_empleado, nombre, departamento FROM chofer";

        String datos[] = new String[3];
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                modelo.addRow(datos);
            }
            rstDatosChofer.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void consultarProveedor() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("PROVEEDOR");
        modelo.addColumn("RFC");
        rstDatosProveedor.setModel(modelo);

        String sql = "SELECT id_proveedor, razon_social, rfc FROM proveedor";

        String datos[] = new String[3];
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                modelo.addRow(datos);
            }
            rstDatosProveedor.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void consultarCombustible() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("COMBUSTIBLE");
        modelo.addColumn("PRECIO");
        rstDatosCombustible.setModel(modelo);

        String sql = "SELECT id_combustible, tipo, precio FROM combustible";

        String datos[] = new String[3];
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                modelo.addRow(datos);
            }
            rstDatosCombustible.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void consultarVehiculo(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("MARCA");
        modelo.addColumn("MODELO");
        modelo.addColumn("COLOR");
        modelo.addColumn("PLACA");
        rstDatosVehiculo.setModel(modelo);

        String sql = "SELECT marca, modelo, color, placa FROM vehiculo";

        String datos[] = new String[4];
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                modelo.addRow(datos);
            }
            rstDatosVehiculo.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //Llenar combobox
    public void llena_comboDeptoChofer() {
        rscDeptoChofer.removeAllItems();
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT id_departamento, nombre_departamento FROM departamento");
            rscDeptoChofer.addItem("--Seleccione uno--");
            while (rs.next()) {
                rscDeptoChofer.addItem(rs.getString(2));
            }

        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void llena_comboProveedorCombustible() {
        rscProveedorCombustible.removeAllItems();
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT razon_social FROM proveedor");
            rscProveedorCombustible.addItem("--Seleccione uno--");
            while (rs.next()) {
                rscProveedorCombustible.addItem(rs.getString(1));
            }

        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void llena_comboDeptoVehiculo(){
        rscDeptoVehiculo.removeAllItems();
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT nombre_departamento FROM departamento");
            rscDeptoVehiculo.addItem("--Seleccione uno--");
            while (rs.next()) {
                rscDeptoVehiculo.addItem(rs.getString(1));
            }

        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    //Consultar ID
    public void consultarIdDeptoToChofer() {
        Statement st;
        try {
            String sql = "SELECT id_departamento FROM departamento WHERE nombre_departamento = '" + rscDeptoChofer.getSelectedItem() + "'";
            PreparedStatement ps = con.prepareStatement(sql);
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                txtIdDeptoChofer.setText(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void consultarIdProveedorCombustible() {
        Statement st;
        try {
            String sql = "SELECT id_proveedor FROM proveedor WHERE razon_social = '" + rscProveedorCombustible.getSelectedItem() + "'";
            PreparedStatement ps = con.prepareStatement(sql);
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                txtIdProveedorCombustible.setText(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void consultarIdDeptoVehiculo(){
        Statement st;
        try {
            String sql = "SELECT id_departamento FROM departamento WHERE nombre_departamento = '" + rscDeptoVehiculo.getSelectedItem() + "'";
            PreparedStatement ps = con.prepareStatement(sql);
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                txtIdDeptoVehiculo.setText(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void consultarIdvehiculo(){
        Statement st;
        try {
            String sql = "SELECT id_vehiculo FROM vehiculo WHERE placa = '" + txtPlacavehiculo.getText() + "'";
            PreparedStatement ps = con.prepareStatement(sql);
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                txtIdVehiculo.setText(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    
    //Consultar datos al dar clic a la tabla
    public void consultarDatosChofer() {
        String sql = "SELECT id_chofer, edad, nss, tipo_sangre, tipo_licencia, m_pago FROM chofer WHERE numero_empleado = '" + txtNumEmpleadoChofer.getText() + "'";
        Statement st;
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                txtIdChofer.setText(rs.getString(1));
                txtEdadChofer.setText(rs.getString(2));
                txtNSSChofer.setText(rs.getString(3));
                rscSangreChofer.setSelectedItem(rs.getString(4));
                rscLicenciaChofer.setSelectedItem(rs.getString(5));
                rscMetodoPagoChofer.setSelectedItem(rs.getString(6));

            }

        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void consultarDatosProveedor() {
        String sql = "SELECT razon_social, direccion, rfc, telefono FROM proveedor WHERE id_proveedor = '" + txtIdProveedor.getText() + "'";
        Statement st;
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                txtNombreProveedor.setText(rs.getString(1));
                txtDireccionProveedor.setText(rs.getString(2));
                txtRFCProveedor.setText(rs.getString(3));
                txtTelefonoProveedor.setText(rs.getString(4));
            }
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void consultarDatosCombustible() {
        
        String sql = "SELECT tipo, precio, proveedor FROM combustible WHERE id_combustible = '" + txtIdCombustible.getText() + "'";
        Statement st;
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                txtTipoCombustible.setText(rs.getString(1));
                txtPrecioCombustible.setText(rs.getString(2));
                txtIdProveedorCombustible.setText(rs.getString(3));    
            }
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void consultarDatosVehiculo() {
        
        String sql = "SELECT marca, modelo, proveedor FROM combustible WHERE id_combustible = '" + txtIdCombustible.getText() + "'";
        Statement st;
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                txtTipoCombustible.setText(rs.getString(1));
                txtPrecioCombustible.setText(rs.getString(2));
                txtIdProveedorCombustible.setText(rs.getString(3));    
            }
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    //Consultar combobox a partir de un ID
    public void consultarDeptoChofer() {

        String sql = "SELECT nombre_departamento FROM departamento WHERE id_departamento = '" + txtIdDeptoChofer.getText() + "'";

        String datos[] = new String[1];
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                rscDeptoChofer.setSelectedItem(rs.getString(1));
            }

        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void consultarProveedorCombustible(){
        String sql = "SELECT razon_social FROM proveedor WHERE id_proveedor = '" + txtIdProveedorCombustible.getText() + "'";

        String datos[] = new String[1];
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                rscProveedorCombustible.setSelectedItem(rs.getString(1));
            }

        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarChofer;
    public javax.swing.JButton btnActualizarCombustible;
    public javax.swing.JButton btnActualizarDepto;
    public javax.swing.JButton btnActualizarProveedor;
    public javax.swing.JButton btnActualizarVehiculo;
    public javax.swing.JButton btnBorrarProveedor;
    private javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnChofer;
    public javax.swing.JButton btnCombustible;
    public javax.swing.JButton btnDepartamento;
    public javax.swing.JButton btnEliminarChofer;
    public javax.swing.JButton btnEliminarDepto;
    public javax.swing.JButton btnEliminarVehiculo;
    public javax.swing.JButton btnEstadisticas;
    public javax.swing.JButton btnGuardarChofer;
    public javax.swing.JButton btnGuardarCombustible;
    public javax.swing.JButton btnGuardarDepto;
    public javax.swing.JButton btnGuardarProveedor;
    public javax.swing.JButton btnGuardarVehiculo;
    public javax.swing.JButton btnInicio;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnLimpiarChofer;
    public javax.swing.JButton btnLimpiarCombustible;
    public javax.swing.JButton btnLimpiarProveedor;
    public javax.swing.JButton btnLimpiarVehiculo;
    private javax.swing.JButton btnMinimizar;
    public javax.swing.JButton btnProveedor;
    public javax.swing.JButton btnTicket;
    public javax.swing.JButton btnVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jpnBarra;
    public javax.swing.JPanel jpnChofer;
    public javax.swing.JPanel jpnCombustible;
    private javax.swing.JPanel jpnControl;
    public javax.swing.JPanel jpnDepartamento;
    public javax.swing.JPanel jpnEstadisticas;
    public javax.swing.JPanel jpnInicio;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnModulo;
    public javax.swing.JPanel jpnProveedor;
    public javax.swing.JPanel jpnTicket;
    public javax.swing.JPanel jpnTituloChofer;
    public javax.swing.JPanel jpnTituloCombustible;
    public javax.swing.JPanel jpnTituloDepto;
    public javax.swing.JPanel jpnTituloEstadisticas;
    public javax.swing.JPanel jpnTituloInicio;
    public javax.swing.JPanel jpnTituloProveedor;
    public javax.swing.JPanel jpnTituloTicket;
    public javax.swing.JPanel jpnTituloVehiculo;
    private javax.swing.JPanel jpnTitulos;
    private javax.swing.JPanel jpnTodo;
    public javax.swing.JPanel jpnVehiculo;
    private javax.swing.JScrollPane jsDatosChofer;
    private javax.swing.JScrollPane jsDatosCombustible;
    private javax.swing.JScrollPane jsDatosDepto;
    private javax.swing.JScrollPane jsDatosProveedor;
    private javax.swing.JLabel lblAnioVehiculo;
    private javax.swing.JLabel lblColorVehiculo;
    private javax.swing.JLabel lblDeptoChofer;
    private javax.swing.JLabel lblDeptoVehiculo;
    private javax.swing.JLabel lblDireccionProveedor;
    private javax.swing.JLabel lblEdadChofer;
    private javax.swing.JLabel lblEncargadoDepto;
    private javax.swing.JLabel lblMarcaVehiculo;
    private javax.swing.JLabel lblMetodoPagoChofer;
    private javax.swing.JLabel lblModeloVehiculo;
    private javax.swing.JLabel lblNSSChofer;
    private javax.swing.JLabel lblNombreChofer;
    private javax.swing.JLabel lblNombreCombustible;
    private javax.swing.JLabel lblNombreDepto;
    private javax.swing.JLabel lblNombreProveedor;
    private javax.swing.JLabel lblNumEmpleadoChofer;
    private javax.swing.JLabel lblPlacaVehiculo;
    private javax.swing.JLabel lblPrecioCombustible;
    private javax.swing.JLabel lblProveedorCombustible;
    private javax.swing.JLabel lblRFCProveedor;
    private javax.swing.JLabel lblTelefonoProveedor;
    private javax.swing.JLabel lblTipoLicenciaChofer;
    private javax.swing.JLabel lblTipoSangreChofer;
    private javax.swing.JLabel lblTipoVehiculo;
    private javax.swing.JLabel lblTituloChofer;
    private javax.swing.JLabel lblTituloCombustible;
    private javax.swing.JLabel lblTituloDepto;
    private javax.swing.JLabel lblTituloEstadisticas;
    private javax.swing.JLabel lblTituloInicio;
    private javax.swing.JLabel lblTituloProveedor;
    private javax.swing.JLabel lblTituloTicket;
    private javax.swing.JLabel lblTituloVehiculo;
    public rojerusan.RSComboMetro rscDeptoChofer;
    public rojerusan.RSComboMetro rscDeptoVehiculo;
    public rojerusan.RSComboMetro rscLicenciaChofer;
    public rojerusan.RSComboMetro rscMetodoPagoChofer;
    public rojerusan.RSComboMetro rscProveedorCombustible;
    public rojerusan.RSComboMetro rscSangreChofer;
    public rojerusan.RSComboMetro rscTipoVehiculo;
    public rojerusan.RSTableMetro rstDatosChofer;
    public rojerusan.RSTableMetro rstDatosCombustible;
    public rojerusan.RSTableMetro rstDatosDepto;
    public rojerusan.RSTableMetro rstDatosProveedor;
    public rojerusan.RSTableMetro rstDatosVehiculo;
    public javax.swing.JTextField txtAnioVehiculo;
    public javax.swing.JTextField txtColorVehiculo;
    public javax.swing.JTextField txtDireccionProveedor;
    public javax.swing.JTextField txtEdadChofer;
    public javax.swing.JTextField txtEncargadoDepto;
    public javax.swing.JTextField txtIdChofer;
    public javax.swing.JTextField txtIdCombustible;
    public javax.swing.JTextField txtIdDepto;
    public javax.swing.JTextField txtIdDeptoChofer;
    public javax.swing.JTextField txtIdDeptoVehiculo;
    public javax.swing.JTextField txtIdProveedor;
    public javax.swing.JTextField txtIdProveedorCombustible;
    public javax.swing.JTextField txtIdVehiculo;
    public javax.swing.JTextField txtMarcaVehiculo;
    public javax.swing.JTextField txtModeloVehiculo;
    public javax.swing.JTextField txtNSSChofer;
    public javax.swing.JTextField txtNombreChofer;
    public javax.swing.JTextField txtNombreProveedor;
    public javax.swing.JTextField txtNombredepto;
    public javax.swing.JTextField txtNumEmpleadoChofer;
    public javax.swing.JTextField txtPlacavehiculo;
    public javax.swing.JTextField txtPrecioCombustible;
    public javax.swing.JTextField txtRFCProveedor;
    public javax.swing.JTextField txtTelefonoProveedor;
    public javax.swing.JTextField txtTipoCombustible;
    // End of variables declaration//GEN-END:variables
}
