/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author alexmartinez
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnLogin = new javax.swing.JPanel();
        jpnLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblLetras = new javax.swing.JLabel();
        jpnDatos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuarioLogin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassLogin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblMensajeLogin = new javax.swing.JLabel();
        btnSalirLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 500));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setName("login"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnLogin.setBackground(new java.awt.Color(255, 255, 255));
        jpnLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnLogo.setBackground(new java.awt.Color(0, 0, 0));
        jpnLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otras_Imagenes/Gas Control.png"))); // NOI18N
        jpnLogo.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 300, 200));

        lblLetras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otras_Imagenes/aguja gasolina.png"))); // NOI18N
        jpnLogo.add(lblLetras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 300, 300));

        jpnLogin.add(jpnLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        jpnDatos.setBackground(new java.awt.Color(102, 102, 102));
        jpnDatos.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 5, 5, new java.awt.Color(0, 0, 0)));
        jpnDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Usuario:");
        jpnDatos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 100, 30));

        txtUsuarioLogin.setBackground(new java.awt.Color(102, 102, 102));
        txtUsuarioLogin.setFont(new java.awt.Font("Ayuthaya", 1, 18)); // NOI18N
        txtUsuarioLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuarioLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jpnDatos.add(txtUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 300, 30));

        jLabel4.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Contraseña:");
        jpnDatos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 150, 30));

        txtPassLogin.setBackground(new java.awt.Color(102, 102, 102));
        txtPassLogin.setFont(new java.awt.Font("Ayuthaya", 0, 18)); // NOI18N
        txtPassLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtPassLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jpnDatos.add(txtPassLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 300, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones_login/btnEntrar1.png"))); // NOI18N
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones_login/btnEntrar3.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones_login/btnEntrar2.png"))); // NOI18N
        jpnDatos.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 200, 40));

        lblMensajeLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpnDatos.add(lblMensajeLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 300, 20));

        btnSalirLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones_login/btnSalir.png"))); // NOI18N
        btnSalirLogin.setBorder(null);
        btnSalirLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirLoginActionPerformed(evt);
            }
        });
        jpnDatos.add(btnSalirLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 80, -1));

        jpnLogin.add(jpnDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 600, 500));

        getContentPane().add(jpnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirLoginActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jpnDatos;
    private javax.swing.JPanel jpnLogin;
    private javax.swing.JPanel jpnLogo;
    private javax.swing.JLabel lblLetras;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMensajeLogin;
    private javax.swing.JTextField txtPassLogin;
    private javax.swing.JTextField txtUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
